### ISSUE TITLE
Segmenter here, thanks for this project (and thinking about ways to improve segment!)

### ISSUE THREAD

**Issue by silesky** [kylemcd/segment-next.js#1]
Currently, our react example is quite simple and straightforward -- there's nothing really magical about it:
https://github.com/segmentio/analytics-next/tree/master/packages/browser#react

I'd love to hear from you more about ideas you have and ways we can integrate them into the main library -- you can add issues at https://github.com/segmentio/analytics-next/tree/master/packages/browser / email me at `seth.silesky@segment.com`

FYI: You can find good traits definition here (I just updated them!)
https://github.com/segmentio/analytics-next/blob/master/packages/core/src/events/interfaces.ts#LL456C3-L456C3

**Comment by kylemcd** [comment]
Hey @silesky thanks for the note. What originally spurred this package was when using `analytics-next`, I could not get the first page load event to fire in a next.js app. I assume this is because `window.analytics` isn't mounted when it tries to fire it. In addition to that, because `analytics-next` uses ContextAPI in order to initiate itself, it isn't compatible with Next 13 in its current state. This library is also a lot simpler because it's a very thing wrapper on top of the regular ole `window.analytics` events. 

I wouldn't have the time to make contributions to `analytics-next` but feel free to take any ideas/code I have in this repo and use them there!

**Comment by silesky** [comment]
`AnalyticsBrowser` does not make an initial page call by default as a side-effect -- that behavior is specifically hard-coded into the snippet version.  

> I assume this is because window.analytics isn't mounted when it tries to fire it.
The npm version uses exports; there is no window object.

> ...because analytics-next uses ContextAPI in order to initiate itself
Not sure I follow this!

> it isn't compatible with Next 13 in its current state. 
Big fan of NextJS, and we definitely have customers on Next 13! I have an example repo I just created -- it appears to work as expected
https://github.com/silesky/segment-next-13/blob/main/pages/_app.tsx

<img width="1372" alt="image" src="https://user-images.githubusercontent.com/5115498/222333566-bd6e0a99-df56-49db-ad4e-d0179ac039be.png">
